# Generated by Django 4.0.5 on 2022-06-12 06:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='profile/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalDetailInfo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('nationality', models.CharField(max_length=100)),
                ('freelance', models.CharField(choices=[('Available', 'Available'), ('', 'UnAvailable')], max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('langauge', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('message', models.CharField(max_length=500)),
                ('expreience', models.CharField(max_length=100)),
                ('complete_project', models.PositiveIntegerField()),
                ('happy_customer', models.PositiveIntegerField()),
                ('award_won', models.PositiveIntegerField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.personalinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
