# Generated by Django 4.0.5 on 2022-06-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_personaldetailinfo_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetailinfo',
            name='desc',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='desc',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
