# Generated by Django 4.0.5 on 2022-06-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_personaldetailinfo_desc_personalinfo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailinfo',
            name='phonenumber',
            field=models.CharField(default='+977 9880388741', max_length=20),
            preserve_default=False,
        ),
    ]
