# Generated by Django 4.0.5 on 2022-06-12 07:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_personaldetailinfo_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('plang', models.CharField(max_length=200)),
                ('level', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.personalinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
