# Generated by Django 4.0.5 on 2022-06-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='place',
            new_name='instute_name',
        ),
    ]
