# Generated by Django 4.0.5 on 2022-06-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_place_education_instute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailinfo',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv/'),
        ),
    ]
