# Generated by Django 4.0.5 on 2022-06-12 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_personaldetailinfo_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPortFolio',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='portimg/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
