# Generated by Django 4.0.5 on 2022-06-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_myportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolio',
            name='client',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='langauge',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='preview',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myportfolio',
            name='project',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
