# Generated by Django 4.0.5 on 2022-06-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='exit', unique=True),
            preserve_default=False,
        ),
    ]
