# Generated by Django 4.0.5 on 2022-06-13 12:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
